blueprint:
  name: Motion lights – 10 areas (AND)
  description: >
    Each area works independently.
    Lights and switches turn off only if ALL motion sensors
    are OFF for the defined time.
    Empty areas are ignored.
  domain: automation

  input:

    area_1_motion:
      name: Area 1 – motion sensors
      default: []
      selector:
        entity:
          domain: binary_sensor
          multiple: true
    area_1_lights:
      name: Area 1 – lights
      default: []
      selector:
        entity:
          domain: light
          multiple: true
    area_1_switches:
      name: Area 1 – switches
      default: []
      selector:
        entity:
          domain: switch
          multiple: true
    area_1_delay:
      name: Area 1 – off delay (min)
      default: 15
      selector:
        number:
          min: 1
          max: 240
          unit_of_measurement: min

    area_2_motion:
      name: Area 2 – motion sensors
      default: []
      selector:
        entity:
          domain: binary_sensor
          multiple: true
    area_2_lights:
      name: Area 2 – lights
      default: []
      selector:
        entity:
          domain: light
          multiple: true
    area_2_switches:
      name: Area 2 – switches
      default: []
      selector:
        entity:
          domain: switch
          multiple: true
    area_2_delay:
      name: Area 2 – off delay (min)
      default: 10
      selector:
        number:
          min: 1
          max: 240
          unit_of_measurement: min

    area_3_motion:
      name: Area 3 – motion sensors
      default: []
      selector:
        entity:
          domain: binary_sensor
          multiple: true
    area_3_lights:
      name: Area 3 – lights
      default: []
      selector:
        entity:
          domain: light
          multiple: true
    area_3_switches:
      name: Area 3 – switches
      default: []
      selector:
        entity:
          domain: switch
          multiple: true
    area_3_delay:
      name: Area 3 – off delay (min)
      default: 10
      selector:
        number:
          min: 1
          max: 240
          unit_of_measurement: min

    area_4_motion:
      name: Area 4 – motion sensors
      default: []
      selector:
        entity:
          domain: binary_sensor
          multiple: true
    area_4_lights:
      name: Area 4 – lights
      default: []
      selector:
        entity:
          domain: light
          multiple: true
    area_4_switches:
      name: Area 4 – switches
      default: []
      selector:
        entity:
          domain: switch
          multiple: true
    area_4_delay:
      name: Area 4 – off delay (min)
      default: 10
      selector:
        number:
          min: 1
          max: 240
          unit_of_measurement: min
