blueprint:
  name: Motion lights – 10 areas (AND)
  description: >
    Each area works independently.
    Lights and switches turn off only if ALL motion sensors
    are OFF for the defined time.
    Empty areas are ignored.
  domain: automation

mode: parallel

input:

  area_1_motion:
    name: Area 1 – motion sensors
    default: []
    selector:
      entity:
        domain: binary_sensor
        multiple: true
  area_1_lights:
    name: Area 1 – lights
    default: []
    selector:
      entity:
        domain: light
        multiple: true
  area_1_switches:
    name: Area 1 – switches
    default: []
    selector:
      entity:
        domain: switch
        multiple: true
  area_1_delay:
    name: Area 1 – off delay (min)
    default: 15
    selector:
      number:
        min: 1
        max: 240
        unit_of_measurement: min

  area_2_motion:
    name: Area 2 – motion sensors
    default: []
    selector:
      entity:
        domain: binary_sensor
        multiple: true
  area_2_lights:
    name: Area 2 – lights
    default: []
    selector:
      entity:
        domain: light
        multiple: true
  area_2_switches:
    name: Area 2 – switches
    default: []
    selector:
      entity:
        domain: switch
        multiple: true
  area_2_delay:
    name: Area 2 – off delay (min)
    default: 10
    selector:
      number:
        min: 1
        max: 240
        unit_of_measurement: min

  area_3_motion:
    name: Area 3 – motion sensors
    default: []
    selector:
      entity:
        domain: binary_sensor
        multiple: true
  area_3_lights:
    name: Area 3 – lights
    default: []
    selector:
      entity:
        domain: light
        multiple: true
  area_3_switches:
    name: Area 3 – switches
    default: []
    selector:
      entity:
        domain: switch
        multiple: true
  area_3_delay:
    name: Area 3 – off delay (min)
    default: 10
    selector:
      number:
        min: 1
        max: 240
        unit_of_measurement: min

  area_4_motion:
    name: Area 4 – motion sensors
    default: []
    selector:
      entity:
        domain: binary_sensor
        multiple: true
  area_4_lights:
    name: Area 4 – lights
    default: []
    selector:
      entity:
        domain: light
        multiple: true
  area_4_switches:
    name: Area 4 – switches
    default: []
    selector:
      entity:
        domain: switch
        multiple: true
  area_4_delay:
    name: Area 4 – off delay (min)
    default: 10
    selector:
      number:
        min: 1
        max: 240
        unit_of_measurement: min

  area_5_motion:
    name: Area 5 – motion sensors
    default: []
    selector:
      entity:
        domain: binary_sensor
        multiple: true
  area_5_lights:
    name: Area 5 – lights
    default: []
    selector:
      entity:
        domain: light
        multiple: true
  area_5_switches:
    name: Area 5 – switches
    default: []
    selector:
      entity:
        domain: switch
        multiple: true
  area_5_delay:
    name: Area 5 – off delay (min)
    default: 10
    selector:
      number:
        min: 1
        max: 240
        unit_of_measurement: min

  area_6_motion:
    name: Area 6 – motion sensors
    default: []
    selector:
      entity:
        domain: binary_sensor
        multiple: true
  area_6_lights:
    name: Area 6 – lights
    default: []
    selector:
      entity:
        domain: light
        multiple: true
  area_6_switches:
    name: Area 6 – switches
    default: []
    selector:
      entity:
        domain: switch
        multiple: true
  area_6_delay:
    name: Area 6 – off delay (min)
    default: 10
    selector:
      number:
        min: 1
        max: 240
        unit_of_measurement: min

  area_7_motion:
    name: Area 7 – motion sensors
    default: []
    selector:
      entity:
        domain: binary_sensor
        multiple: true
  area_7_lights:
    name: Area 7 – lights
    default: []
    selector:
      entity:
        domain: light
        multiple: true
  area_7_switches:
    name: Area 7 – switches
    default: []
    selector:
      entity:
        domain: switch
        multiple: true
  area_7_delay:
    name: Area 7 – off delay (min)
    default: 10
    selector:
      number:
        min: 1
        max: 240
        unit_of_measurement: min

  area_8_motion:
    name: Area 8 – motion sensors
    default: []
    selector:
      entity:
        domain: binary_sensor
        multiple: true
  area_8_lights:
    name: Area 8 – lights
    default: []
    selector:
      entity:
        domain: light
        multiple: true
  area_8_switches:
    name: Area 8 – switches
    default: []
    selector:
      entity:
        domain: switch
        multiple: true
  area_8_delay:
    name: Area 8 – off delay (min)
    default: 10
    selector:
      number:
        min: 1
        max: 240
        unit_of_measurement: min

  area_9_motion:
    name: Area 9 – motion sensors
    default: []
    selector:
      entity:
        domain: binary_sensor
        multiple: true
  area_9_lights:
    name: Area 9 – lights
    default: []
    selector:
      entity:
        domain: light
        multiple: true
  area_9_switches:
    name: Area 9 – switches
    default: []
    selector:
      entity:
        domain: switch
        multiple: true
  area_9_delay:
    name: Area 9 – off delay (min)
    default: 10
    selector:
      number:
        min: 1
        max: 240
        unit_of_measurement: min

  area_10_motion:
    name: Area 10 – motion sensors
    default: []
    selector:
      entity:
        domain: binary_sensor
        multiple: true
  area_10_lights:
    name: Area 10 – lights
    default: []
    selector:
      entity:
        domain: light
        multiple: true
  area_10_switches:
    name: Area 10 – switches
    default: []
    selector:
      entity:
        domain: switch
        multiple: true
  area_10_delay:
    name: Area 10 – off delay (min)
    default: 10
    selector:
      number:
        min: 1
        max: 240
        unit_of_measurement: min

trigger:
  - platform: state
    entity_id: >
      {{
        input_area_1_motion +
        input_area_2_motion +
        input_area_3_motion +
        input_area_4_motion +
        input_area_5_motion +
        input_area_6_motion +
        input_area_7_motion +
        input_area_8_motion +
        input_area_9_motion +
        input_area_10_motion
      }}
    to: "on"

action:
  - repeat:
      for_each:
        - motion: !input area_1_motion
          lights: !input area_1_lights
          switches: !input area_1_switches
          delay: !input area_1_delay
        - motion: !input area_2_motion
          lights: !input area_2_lights
          switches: !input area_2_switches
          delay: !input area_2_delay
        - motion: !input area_3_motion
          lights: !input area_3_lights
          switches: !input area_3_switches
          delay: !input area_3_delay
        - motion: !input area_4_motion
          lights: !input area_4_lights
          switches: !input area_4_switches
          delay: !input area_4_delay
        - motion: !input area_5_motion
          lights: !input area_5_lights
          switches: !input area_5_switches
          delay: !input area_5_delay
        - motion: !input area_6_motion
          lights: !input area_6_lights
          switches: !input area_6_switches
          delay: !input area_6_delay
        - motion: !input area_7_motion
          lights: !input area_7_lights
          switches: !input area_7_switches
          delay: !input area_7_delay
        - motion: !input area_8_motion
          lights: !input area_8_lights
          switches: !input area_8_switches
          delay: !input area_8_delay
        - motion: !input area_9_motion
          lights: !input area_9_lights
          switches: !input area_9_switches
          delay: !input area_9_delay
        - motion: !input area_10_motion
          lights: !input area_10_lights
          switches: !input area_10_switches
          delay: !input area_10_delay
      sequence:
        - condition: template
          value_template: "{{ repeat.item.motion | length > 0 }}"

        - wait_for_trigger:
            - platform: state
              entity_id: "{{ repeat.item.motion }}"
              to: "off"
          for:
            minutes: "{{ repeat.item.delay }}"

        - service: homeassistant.turn_off
          target:
            entity_id: >
              {{ repeat.item.lights + repeat.item.switches }}
